using System.Collections.Concurrent;
using System.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.InteropServices;
using Tosh.Runtime;
using Tosh.Language.Parsing;

namespace Tosh.Language.Bridge;

/// <param name="InlineBufferLength">
/// Element count for an out-array parameter: either <c>buffer[n]</c> (C's
/// output-string idiom) or a typed <c>T[n]</c> such as <c>getloadavg</c>'s
/// <c>double[3]</c>. The array is engine-allocated and marshals as a pointer to
/// its first element.
/// </param>
/// <param name="DecodeAsCString">
/// True for <c>buffer[n]</c>, whose bytes are decoded to a string after the
/// call. A typed <c>T[n]</c> comes back as the array itself.
/// </param>
/// <param name="IsSynthesizedLength">
/// The companion length argument generated by a <c>buffer[n]</c> — C's
/// output-string convention is always an adjacent (pointer, length) pair, and
/// declaring it literally would mean writing the size twice. Engine-supplied,
/// so it never appears at the call site or in the result.
/// </param>
/// <param name="Callback">
/// Set when this parameter's declared type is a <c>raw callback</c>. Carried on
/// the parameter rather than looked up from <see cref="ClrType"/> because
/// <see cref="NativeDelegateTypeFactory"/> caches by signature — two callbacks
/// with identical shapes share one emitted type, so the type alone cannot say
/// which declaration a parameter named.
/// </param>
internal sealed record NativeFunctionParameterDefinition(
    string Name,
    string TypeName,
    Type ClrType,
    NativeParameterPassingMode PassingMode,
    int? InlineBufferLength = null,
    bool DecodeAsCString = false,
    bool IsSynthesizedLength = false,
    ToshNativeCallbackDefinition? Callback = null)
{
    public bool IsInlineBuffer => InlineBufferLength is not null;

    /// <summary>
    /// True when the engine supplies this argument rather than the caller: any
    /// <c>out</c> parameter, plus the synthesized length of a <c>buffer[n]</c>.
    /// </summary>
    public bool IsEngineSupplied =>
        PassingMode == NativeParameterPassingMode.Out || IsSynthesizedLength;

    /// <summary>
    /// A byte array already marshals as a pointer to its first element, so an
    /// inline buffer is passed by value rather than by reference even though it
    /// is an <c>out</c> parameter.
    /// </summary>
    public Type DelegateParameterType =>
        IsInlineBuffer || PassingMode == NativeParameterPassingMode.In
            ? ClrType
            : ClrType.MakeByRefType();
}
internal enum NativeFunctionReturnKind
{
    Default,
    CString,
}

/// <summary>
/// How a call decides whether it succeeded. Orthogonal to the result
/// projection: this answers "does it throw", not "what do I get back".
/// </summary>
internal enum NativeErrorConvention
{
    /// <summary>No checking — the raw return value is the result.</summary>
    None,

    /// <summary><c>-&gt; ok</c>: zero is success. sysinfo, uname, close, chdir.</summary>
    Ok,

    /// <summary>
    /// <c>-&gt; count</c>: non-negative is success <em>and is the value</em>.
    /// read, write, readlink, sysconf. When paired with a <c>buffer[n]</c> the
    /// count is the buffer's true length, which is what makes readlink safe.
    /// </summary>
    Count,

    /// <summary><c>where (…)</c>: a user predicate over the return value.</summary>
    Predicate,
}

internal sealed record NativeFunctionReturnDefinition(
    string TypeName,
    Type ClrType,
    NativeFunctionReturnKind Kind,
    NativeErrorConvention Convention = NativeErrorConvention.None);

internal sealed class NativeFunctionCommand : IShellCommand, ICommandResolutionMetadata
{
    private readonly Delegate _delegate;
    private readonly IReadOnlyList<NativeFunctionParameterDefinition> _parameters;
    private readonly NativeFunctionReturnDefinition? _return;
    private readonly Func<object?, CancellationToken, ValueTask<bool>>? _successPredicate;

    public NativeFunctionCommand(
        string moduleName,
        string name,
        string symbolName,
        NativeLibraryBinding binding,
        IReadOnlyList<NativeFunctionParameterDefinition> parameters,
        NativeFunctionReturnDefinition? @return,
        CallingConvention callingConvention,
        Func<object?, CancellationToken, ValueTask<bool>>? successPredicate = null)
    {
        ModuleName = moduleName;
        Name = name;
        SymbolName = symbolName;
        Binding = binding;
        _parameters = parameters;
        _return = @return;
        _successPredicate = successPredicate;
        ReturnTypeName = @return?.TypeName;
        _delegate = CreateDelegate(binding.Handle, symbolName, parameters, @return?.ClrType, callingConvention);
    }

    public string ModuleName { get; }

    public string Name { get; }

    public string SymbolName { get; }

    public NativeLibraryBinding Binding { get; }

    public string? ReturnTypeName { get; }

    public string Description => $"Invokes native export '{SymbolName}' from '{Binding.Target}'.";

    /// <summary>
    /// How many arguments a caller supplies. `out` parameters are
    /// engine-allocated and the length companion of a <c>buffer[n]</c> is
    /// synthesized, so neither counts.
    /// </summary>
    public int CallableParameterCount =>
        _parameters.Count(static parameter => !parameter.IsEngineSupplied);

    /// <summary>
    /// Rendered as the declaration rather than the raw ABI signature: the
    /// synthesized length of a <c>buffer[n]</c> is plumbing, and showing it
    /// would suggest an argument the caller must pass.
    /// </summary>
    public string Usage
    {
        get
        {
            var parameters = _parameters
                .Where(static parameter => !parameter.IsSynthesizedLength)
                .Select(static parameter => parameter.PassingMode switch
                {
                    NativeParameterPassingMode.Out => $"out {parameter.Name}: {parameter.TypeName}",
                    NativeParameterPassingMode.Ref => $"ref {parameter.Name}: {parameter.TypeName}",
                    _ => parameter.TypeName,
                });

            var signature = $"{ModuleName}.{Name}({string.Join(", ", parameters)})";
            return ReturnTypeName is null ? signature : $"{signature} -> {ReturnTypeName}";
        }
    }

    public CommandResolutionKind ResolutionKind => CommandResolutionKind.Function;

    public async IAsyncEnumerable<object?> ExecuteAsync(CommandContext context)
    {
        // `out` parameters are engine-allocated and do not appear at the call
        // site: the callee fills them and reads nothing, so there is nothing for
        // a caller to supply but a placeholder. `ref` parameters stay, because
        // the callee reads them (poll's `events`, select's `fd_set`).
        var callableCount = _parameters.Count(static parameter => !parameter.IsEngineSupplied);

        if (context.Arguments.Count != callableCount)
        {
            var outCount = _parameters.Count - callableCount;
            var hint = outCount == 0
                ? $"'{ModuleName}.{Name}' requires {callableCount} argument(s)"
                : $"'{ModuleName}.{Name}' requires {callableCount} argument(s); its {outCount} 'out' parameter(s) are supplied by the engine";

            throw context.CreateDiagnostic(
                code: "tosh.runtime.native_argument_count_mismatch",
                title: $"Native function '{ModuleName}.{Name}' expects {callableCount} argument(s) but received {context.Arguments.Count}.",
                label: hint);
        }

        var convertedArguments = new object?[_parameters.Count];
        var bufferBackedParameters = new List<(int Index, NativeFunctionParameterDefinition Parameter, NativeBuffer Buffer)>();
        var callerArgumentIndex = 0;

        for (var index = 0; index < _parameters.Count; index++)
        {
            var parameter = _parameters[index];

            if (parameter.IsInlineBuffer)
            {
                convertedArguments[index] = Array.CreateInstance(
                    parameter.ClrType.GetElementType()!,
                    parameter.InlineBufferLength!.Value);
                continue;
            }

            if (parameter.IsSynthesizedLength)
            {
                convertedArguments[index] = TypeConversion.TryConvert(
                    _parameters[index - 1].InlineBufferLength!.Value, parameter.ClrType, out var length)
                    ? length
                    : NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Out)
            {
                convertedArguments[index] = NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            var value = context.Arguments[callerArgumentIndex];
            var argumentIndex = callerArgumentIndex;
            callerArgumentIndex++;

            if (parameter.Callback is { } callbackDefinition)
            {
                if (value is not IShellCallable callable)
                {
                    throw context.CreateDiagnostic(
                        code: "tosh.runtime.native_callback_expects_function",
                        title: $"Parameter '{parameter.Name}' of '{ModuleName}.{Name}' expects the callback '{callbackDefinition.Name}'.",
                        argumentIndex: argumentIndex,
                        label: $"pass a function reference such as '&my_handler'");
                }

                var thunk = NativeCallbackThunkFactory.Create(
                    callbackDefinition, callable, context, Environment.CurrentManagedThreadId);

                // Rooted for the life of the library: a callee that stores the
                // pointer (GLFW's window callbacks) outlives this call, and a
                // collected thunk leaves native code calling freed memory.
                NativeCallbackThunkFactory.Root(Binding, thunk);

                convertedArguments[index] = thunk;
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Ref && value is NativeBuffer nativeBuffer)
            {
                // Both the seeding read and the write-back below go through raw
                // pointers, so the buffer's own bounds checks do not apply. An
                // undersized buffer would read adjacent heap and then corrupt it.
                var required = NativeInteropUtilities.SizeOf(parameter.ClrType);

                if (nativeBuffer.ByteLength < required)
                {
                    throw context.CreateDiagnostic(
                        code: "tosh.runtime.native_buffer_range",
                        title: $"'{parameter.Name}' needs a {required}-byte buffer but received {nativeBuffer.ByteLength} bytes.",
                        argumentIndex: callerArgumentIndex - 1,
                        label: $"allocate with 'alloc buf = {parameter.TypeName}'");
                }

                convertedArguments[index] = NativeInteropUtilities.ReadValue(parameter.ClrType, nativeBuffer.Pointer);
                bufferBackedParameters.Add((index, parameter, nativeBuffer));
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Ref && value is null)
            {
                convertedArguments[index] = NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            if (!TypeConversion.TryConvert(value, parameter.ClrType, out var converted))
            {
                throw context.CreateDiagnostic(
                    code: "tosh.runtime.native_argument_type_conversion_failed",
                    title: $"Argument {argumentIndex + 1} for native function '{ModuleName}.{Name}' could not be converted to '{parameter.TypeName}'.",
                    argumentIndex: argumentIndex,
                    label: $"argument {argumentIndex + 1} expects {parameter.TypeName}");
            }

            convertedArguments[index] = converted;
        }

        object? result;
        int errno;

        // A callback cannot throw across the native frames it runs on, so it
        // records its failure and returns a default instead. This scope is
        // where that failure becomes an exception again, once the native frames
        // are gone and throwing is legal.
        using (var callbackScope = new NativeCallbackScope())
        {
            try
            {
                result = _delegate.DynamicInvoke(convertedArguments);

                // Must be read before any other managed work: the captured value is
                // per-thread and the next P/Invoke overwrites it.
                errno = Marshal.GetLastPInvokeError();
            }
            catch (TargetInvocationException exception) when (exception.InnerException is not null)
            {
                throw new InvalidOperationException(exception.InnerException.Message, exception.InnerException);
            }

            // Takes precedence over the native return value: a call whose
            // callback failed did not do what the script asked, whatever the
            // library reported.
            if (callbackScope.Failure is { } failure)
            {
                throw failure;
            }
        }

        foreach (var bufferBackedParameter in bufferBackedParameters)
        {
            NativeInteropUtilities.WriteValue(bufferBackedParameter.Buffer.Pointer, convertedArguments[bufferBackedParameter.Index]);
        }

        // The synthesized length of a buffer[n] is plumbing, not a result.
        var byRefParameters = _parameters
            .Select((parameter, index) => (Parameter: parameter, Index: index))
            .Where(static entry =>
                entry.Parameter.PassingMode != NativeParameterPassingMode.In &&
                !entry.Parameter.IsSynthesizedLength)
            .ToArray();

        // The success contract decides whether we throw. It is orthogonal to the
        // projection below, which decides what a successful call yields.
        var convention = _return?.Convention ?? NativeErrorConvention.None;

        if (convention != NativeErrorConvention.None &&
            !await IsSuccessAsync(convention, result, context.CancellationToken))
        {
            var failure = new NativeError(Binding.Target, SymbolName, result, errno);

            // Marks this as a *thrown value* rather than an incidental runtime
            // exception. The engine's expression-level handlers rethrow anything
            // carrying it, so `catch (e)` binds the NativeError itself and
            // `$e.Errno` works — without it the error was flattened to a
            // ToshDiagnosticException before any catch could see it.
            failure.Data["tosh.thrown"] = true;

            // Without a span the renderer underlines the start of the script
            // rather than the failing call.
            if (context.Invocation?.CommandSpan is { } callSpan)
            {
                failure.Span = callSpan;
            }

            throw failure;
        }

        // `count` carries the true length of an inline buffer. readlink(2) does
        // not NUL-terminate its output, so without this the decoded string would
        // trail whatever was previously in the buffer.
        var bufferLength = convention == NativeErrorConvention.Count ? ToInt32(result) : (int?)null;

        if ((_return is null || _return.ClrType == typeof(void)) && byRefParameters.Length == 0)
        {
            yield break;
        }

        if (byRefParameters.Length == 1 &&
            (convention != NativeErrorConvention.None || _return is null || _return.ClrType == typeof(void)))
        {
            // A checked call has already consumed its return value as the
            // pass/fail signal, so the out parameter is the result.
            yield return ProjectByRefValue(byRefParameters[0].Parameter, convertedArguments[byRefParameters[0].Index], bufferLength);
            yield break;
        }

        if (byRefParameters.Length == 0)
        {
            // `TS-P2-88`. A checked call spends its return value on the success
            // decision above, so yielding it again puts a status code into the
            // pipeline: `LibC.chdir("/tmp")` emitted `0`, and a render loop
            // calling `SDL_SetRenderDrawColor` printed a column of zeroes under
            // the window. The multi-out path had always known this — see
            // `CreateCompositeResult`, which omits `ReturnValue` for the same
            // reason — and only this zero-out path disagreed.
            //
            // `count` is the deliberate exception, on both paths: a byte count is
            // a genuine result that happens to double as the error signal.
            //
            // `Predicate` (a `where (…)` contract) keeps yielding, which is the
            // *opposite* of what `CreateCompositeResult` does with it. That
            // asymmetry is left alone rather than resolved here: a custom
            // predicate is written precisely when the return is not a standard
            // status — `-> ptr where (_ != 0)` guards a handle the caller needs —
            // so dropping it would break the case it exists for.
            if (convention is not NativeErrorConvention.Ok)
            {
                yield return ConvertReturn(result, _return!);
            }

            yield break;
        }

        yield return CreateCompositeResult(result, convertedArguments, byRefParameters, _return, convention, bufferLength);
        await Task.CompletedTask;
    }

    private async ValueTask<bool> IsSuccessAsync(
        NativeErrorConvention convention,
        object? result,
        CancellationToken cancellationToken)
    {
        return convention switch
        {
            NativeErrorConvention.Ok => ToInt64(result) == 0,
            NativeErrorConvention.Count => ToInt64(result) >= 0,
            NativeErrorConvention.Predicate => _successPredicate is not null &&
                                               await _successPredicate(result, cancellationToken),
            _ => true,
        };
    }

    private static long ToInt64(object? value) => value switch
    {
        null => 0,
        IntPtr pointer => pointer.ToInt64(),
        UIntPtr pointer => unchecked((long)pointer.ToUInt64()),
        IConvertible convertible => convertible.ToInt64(null),
        _ => 0,
    };

    private static int ToInt32(object? value)
    {
        var wide = ToInt64(value);
        return wide is > int.MaxValue or < int.MinValue ? int.MaxValue : (int)wide;
    }

    private static object CreateCompositeResult(
        object? returnValue,
        IReadOnlyList<object?> convertedArguments,
        IReadOnlyList<(NativeFunctionParameterDefinition Parameter, int Index)> byRefParameters,
        NativeFunctionReturnDefinition? @return,
        NativeErrorConvention convention,
        int? bufferLength)
    {
        IDictionary<string, object?> fields = new ExpandoObject();

        // A checked call has already spent its return value on the success
        // decision, so repeating it as `ReturnValue` is noise — except for
        // `count`, where the value is a genuine result.
        var includeReturnValue = @return is not null &&
                                 @return.ClrType != typeof(void) &&
                                 convention is NativeErrorConvention.None or NativeErrorConvention.Count;

        if (includeReturnValue)
        {
            fields["ReturnValue"] = ConvertReturn(returnValue, @return!);
        }

        foreach (var (parameter, index) in byRefParameters)
        {
            fields[parameter.Name] = ProjectByRefValue(parameter, convertedArguments[index], bufferLength);
        }

        return fields;
    }

    /// <summary>
    /// An inline <c>buffer[n]</c> comes back as raw bytes; the caller asked for a
    /// string.
    /// </summary>
    /// <param name="bufferLength">
    /// The true length when the call declared <c>-&gt; count</c>. Without it,
    /// decoding stops at the first NUL — correct for gethostname and getcwd, but
    /// wrong for readlink and read, which do not terminate their output.
    /// </param>
    private static object? ProjectByRefValue(
        NativeFunctionParameterDefinition parameter,
        object? value,
        int? bufferLength = null)
    {
        // A typed T[n] out-array is already the result; only a cstring buffer
        // needs decoding.
        if (!parameter.DecodeAsCString || value is not byte[] bytes)
        {
            return value;
        }

        int length;

        if (bufferLength is { } declared)
        {
            length = Math.Clamp(declared, 0, bytes.Length);
        }
        else
        {
            length = Array.IndexOf(bytes, (byte)0);
            if (length < 0) length = bytes.Length;
        }

        return NativeInteropUtilities.DecodeCString(bytes.AsSpan(0, length));
    }

    private static object? ConvertReturn(object? result, NativeFunctionReturnDefinition @return)
    {
        if (@return.Kind == NativeFunctionReturnKind.CString)
        {
            return result is IntPtr pointer
                ? (pointer == IntPtr.Zero ? null : Marshal.PtrToStringAnsi(pointer))
                : result;
        }

        // `count` marshals as ssize_t (pointer-sized) for ABI correctness, but a
        // count is a number, not an address — surfacing IntPtr would make every
        // caller convert before they could do arithmetic on it.
        if (@return.Convention == NativeErrorConvention.Count)
        {
            return ToInt64(result);
        }

        return result;
    }

    private static Delegate CreateDelegate(
        IntPtr libraryHandle,
        string symbolName,
        IReadOnlyList<NativeFunctionParameterDefinition> parameters,
        Type? returnType,
        CallingConvention callingConvention)
    {
        var export = NativeLibrary.GetExport(libraryHandle, symbolName);
        var delegateType = NativeDelegateTypeFactory.GetOrCreate(
            parameters,
            returnType ?? typeof(void),
            callingConvention);
        return Marshal.GetDelegateForFunctionPointer(export, delegateType);
    }
}

internal static class NativeDelegateTypeFactory
{
    // Shares NativeInteropModule with NativeStructTypeFactory: delegate
    // signatures reference emitted raw-struct types, so both live in one
    // dynamic assembly.
    private static ModuleBuilder Module => NativeInteropModule.Module;
    private static readonly ConcurrentDictionary<string, Type> Cache = new(StringComparer.Ordinal);
    private static int _nextTypeId;

    public static Type GetOrCreate(IReadOnlyList<NativeFunctionParameterDefinition> parameters, Type returnType, CallingConvention callingConvention)
    {
        var key = string.Join("|", parameters.Select(static parameter => $"{parameter.DelegateParameterType.AssemblyQualifiedName}@{parameter.PassingMode}"))
                  + "->"
                  + returnType.AssemblyQualifiedName
                  + "@"
                  + callingConvention;

        return Cache.GetOrAdd(key, _ => Create(parameters, returnType, callingConvention));
    }

    private static Type Create(IReadOnlyList<NativeFunctionParameterDefinition> parameters, Type returnType, CallingConvention callingConvention)
    {
        var typeBuilder = Module.DefineType(
            "ToshNativeDelegate" + Interlocked.Increment(ref _nextTypeId),
            TypeAttributes.Class | TypeAttributes.Public | TypeAttributes.Sealed | TypeAttributes.AnsiClass | TypeAttributes.AutoClass,
            typeof(MulticastDelegate));

        var attributeConstructor = typeof(UnmanagedFunctionPointerAttribute).GetConstructor([typeof(CallingConvention)])
                                   ?? throw new InvalidOperationException("Unable to locate UnmanagedFunctionPointerAttribute constructor.");

        // SetLastError is what makes errno readable after the call. Without it
        // Marshal.GetLastPInvokeError() returns whatever the previous P/Invoke
        // left behind, so a failure diagnostic would name an unrelated error.
        var setLastError = typeof(UnmanagedFunctionPointerAttribute).GetField(
                               nameof(UnmanagedFunctionPointerAttribute.SetLastError))
                           ?? throw new InvalidOperationException("Unable to locate UnmanagedFunctionPointerAttribute.SetLastError.");

        typeBuilder.SetCustomAttribute(new CustomAttributeBuilder(
            attributeConstructor,
            [callingConvention],
            [setLastError],
            [true]));

        var constructor = typeBuilder.DefineConstructor(
            MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.RTSpecialName,
            CallingConventions.Standard,
            [typeof(object), typeof(IntPtr)]);
        constructor.SetImplementationFlags(MethodImplAttributes.Runtime | MethodImplAttributes.Managed);

        var invoke = typeBuilder.DefineMethod(
            "Invoke",
            MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.NewSlot | MethodAttributes.Virtual,
            returnType,
            parameters.Select(static parameter => parameter.DelegateParameterType).ToArray());
        invoke.SetImplementationFlags(MethodImplAttributes.Runtime | MethodImplAttributes.Managed);

        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var attributes = parameter.PassingMode switch
            {
                NativeParameterPassingMode.Out => ParameterAttributes.Out,
                NativeParameterPassingMode.Ref => ParameterAttributes.In | ParameterAttributes.Out,
                _ => ParameterAttributes.None,
            };
            invoke.DefineParameter(index + 1, attributes, parameter.Name);
        }

        return typeBuilder.CreateType()
               ?? throw new InvalidOperationException("Failed to create native delegate type.");
    }
}
