using System.Collections.Concurrent;
using System.Globalization;
using System.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.InteropServices;
using Tosh.Runtime;
using Tosh.Language.Parsing;

namespace Tosh.Language.Bridge;

/// <param name="InlineBufferLength">
/// Element count for an out-array parameter: either <c>buffer[n]</c> (C's
/// output-string idiom) or a typed <c>T[n]</c> such as <c>getloadavg</c>'s
/// <c>double[3]</c>. The array is engine-allocated and marshals as a pointer to
/// its first element.
/// </param>
/// <param name="DecodeAsCString">
/// True for <c>buffer[n]</c>, whose bytes are decoded to a string after the
/// call. A typed <c>T[n]</c> comes back as the array itself.
/// </param>
/// <param name="IsCStringPointer">
/// True for <c>out</c>/<c>ref cstring</c> — a <c>char**</c>. The slot marshals as
/// <c>IntPtr</c> by reference and the pointer the callee leaves there is decoded
/// after the call. Distinct from <see cref="DecodeAsCString"/>, which decodes a
/// buffer the engine allocated; here the bytes belong to the callee
/// (<c>TS-P3-26</c>).
/// </param>
/// <param name="OwnsCStringInput">
/// True for an <em>input</em> <c>cstring</c> in a binding that also has a by-ref
/// one. The default marshaller allocates a temporary for an input string and frees
/// it the moment the call returns — but a <c>char*</c> the callee hands back often
/// points *into* that input (<c>strtol</c>'s <c>endptr</c> is the canonical case),
/// so decoding it afterwards would read freed memory. This call allocates the input
/// itself and keeps it alive until the by-ref pointers have been decoded.
/// </param>
/// <param name="IsSynthesizedLength">
/// The companion length argument generated by a <c>buffer[n]</c> — C's
/// output-string convention is always an adjacent (pointer, length) pair, and
/// declaring it literally would mean writing the size twice. Engine-supplied,
/// so it never appears at the call site or in the result.
/// </param>
/// <param name="Callback">
/// Set when this parameter's declared type is a <c>raw callback</c>. Carried on
/// the parameter rather than looked up from <see cref="ClrType"/> because
/// <see cref="NativeDelegateTypeFactory"/> caches by signature — two callbacks
/// with identical shapes share one emitted type, so the type alone cannot say
/// which declaration a parameter named.
/// </param>
internal sealed record NativeFunctionParameterDefinition(
    string Name,
    string TypeName,
    Type ClrType,
    NativeParameterPassingMode PassingMode,
    int? InlineBufferLength = null,
    bool DecodeAsCString = false,
    bool IsCStringPointer = false,
    bool OwnsCStringInput = false,
    bool IsSynthesizedLength = false,
    ToshNativeCallbackDefinition? Callback = null)
{
    public bool IsInlineBuffer => InlineBufferLength is not null;

    /// <summary>
    /// True when the engine supplies this argument rather than the caller: any
    /// <c>out</c> parameter, plus the synthesized length of a <c>buffer[n]</c>.
    /// </summary>
    public bool IsEngineSupplied =>
        PassingMode == NativeParameterPassingMode.Out || IsSynthesizedLength;

    /// <summary>
    /// A byte array already marshals as a pointer to its first element, so an
    /// inline buffer is passed by value rather than by reference even though it
    /// is an <c>out</c> parameter.
    /// </summary>
    public Type DelegateParameterType =>
        IsInlineBuffer || PassingMode == NativeParameterPassingMode.In
            ? ClrType
            : ClrType.MakeByRefType();
}
internal enum NativeFunctionReturnKind
{
    Default,
    CString,
}

/// <summary>
/// How a call decides whether it succeeded. Orthogonal to the result
/// projection: this answers "does it throw", not "what do I get back".
/// </summary>
internal enum NativeErrorConvention
{
    /// <summary>No checking — the raw return value is the result.</summary>
    None,

    /// <summary><c>-&gt; ok</c>: zero is success. sysinfo, uname, close, chdir.</summary>
    Ok,

    /// <summary>
    /// <c>-&gt; count</c>: non-negative is success <em>and is the value</em>.
    /// read, write, readlink, sysconf. When paired with a <c>buffer[n]</c> the
    /// count is the buffer's true length, which is what makes readlink safe.
    /// </summary>
    Count,

    /// <summary><c>where (…)</c>: a user predicate over the return value.</summary>
    Predicate,
}

internal sealed record NativeFunctionReturnDefinition(
    string TypeName,
    Type ClrType,
    NativeFunctionReturnKind Kind,
    NativeErrorConvention Convention = NativeErrorConvention.None);

internal sealed class NativeFunctionCommand : IShellCommand, ICommandResolutionMetadata
{
    private readonly Delegate? _delegate;
    private readonly IReadOnlyList<NativeFunctionParameterDefinition> _parameters;
    private readonly NativeFunctionReturnDefinition? _return;
    private readonly Func<object?, CancellationToken, ValueTask<bool>>? _successPredicate;

    /// <summary>Delegates for variadic call shapes already seen, keyed by the tail.</summary>
    private readonly ConcurrentDictionary<string, Delegate> _variadicDelegates = new(StringComparer.Ordinal);

    public NativeFunctionCommand(
        string moduleName,
        string name,
        string symbolName,
        NativeLibraryBinding binding,
        IReadOnlyList<NativeFunctionParameterDefinition> parameters,
        NativeFunctionReturnDefinition? @return,
        CallingConvention callingConvention,
        Func<object?, CancellationToken, ValueTask<bool>>? successPredicate = null,
        bool isVariadic = false,
        Action<string, string, string>? warn = null)
    {
        ModuleName = moduleName;
        Name = name;
        SymbolName = symbolName;
        Binding = binding;
        _parameters = parameters;
        _return = @return;
        _successPredicate = successPredicate;
        ReturnTypeName = @return?.TypeName;
        IsVariadic = isVariadic;
        _callingConvention = callingConvention;
        _warn = warn;

        // A variadic binding has no single signature to bind to: the tail is only
        // known at the call site, so the delegate is built there and cached by shape
        // (`TS-P3-24`). A fixed binding still resolves its symbol here, so a
        // misspelling is reported when the binding is first reached rather than
        // whenever it happens to be called.
        _delegate = isVariadic
            ? null
            : CreateDelegate(binding.Handle, binding.Target, symbolName, parameters, @return?.ClrType, callingConvention);
    }

    /// <summary>Whether the binding ends in a C <c>...</c> tail.</summary>
    public bool IsVariadic { get; }

    private readonly CallingConvention _callingConvention;
    private readonly Action<string, string, string>? _warn;

    public string ModuleName { get; }

    public string Name { get; }

    public string SymbolName { get; }

    public NativeLibraryBinding Binding { get; }

    public string? ReturnTypeName { get; }

    public string Description => $"Invokes native export '{SymbolName}' from '{Binding.Target}'.";

    /// <summary>
    /// How many arguments a caller supplies. `out` parameters are
    /// engine-allocated and the length companion of a <c>buffer[n]</c> is
    /// synthesized, so neither counts.
    /// </summary>
    public int CallableParameterCount =>
        _parameters.Count(static parameter => !parameter.IsEngineSupplied);

    /// <summary>
    /// Rendered as the declaration rather than the raw ABI signature: the
    /// synthesized length of a <c>buffer[n]</c> is plumbing, and showing it
    /// would suggest an argument the caller must pass.
    /// </summary>
    public string Usage
    {
        get
        {
            var parameters = _parameters
                .Where(static parameter => !parameter.IsSynthesizedLength)
                .Select(static parameter => parameter.PassingMode switch
                {
                    NativeParameterPassingMode.Out => $"out {parameter.Name}: {parameter.TypeName}",
                    NativeParameterPassingMode.Ref => $"ref {parameter.Name}: {parameter.TypeName}",
                    _ => parameter.TypeName,
                });

            var signature = $"{ModuleName}.{Name}({string.Join(", ", parameters)})";
            return ReturnTypeName is null ? signature : $"{signature} -> {ReturnTypeName}";
        }
    }

    public CommandResolutionKind ResolutionKind => CommandResolutionKind.Function;

    public async IAsyncEnumerable<object?> ExecuteAsync(CommandContext context)
    {
        // `out` parameters are engine-allocated and do not appear at the call
        // site: the callee fills them and reads nothing, so there is nothing for
        // a caller to supply but a placeholder. `ref` parameters stay, because
        // the callee reads them (poll's `events`, select's `fd_set`).
        var callableCount = _parameters.Count(static parameter => !parameter.IsEngineSupplied);

        // A variadic binding fixes only its leading parameters; the tail is whatever
        // the call site pushed, so "too many" is the normal case (`TS-P3-24`).
        if (IsVariadic ? context.Arguments.Count < callableCount : context.Arguments.Count != callableCount)
        {
            var outCount = _parameters.Count - callableCount;
            var atLeast = IsVariadic ? "at least " : string.Empty;
            var hint = outCount == 0
                ? $"'{ModuleName}.{Name}' requires {atLeast}{callableCount} argument(s)"
                : $"'{ModuleName}.{Name}' requires {atLeast}{callableCount} argument(s); its {outCount} 'out' parameter(s) are supplied by the engine";

            throw context.CreateDiagnostic(
                code: "tosh.runtime.native_argument_count_mismatch",
                title: $"Native function '{ModuleName}.{Name}' expects {atLeast}{callableCount} argument(s) but received {context.Arguments.Count}.",
                label: hint);
        }

        // Native memory this call allocated for `ref cstring` inputs, released once
        // the callee can no longer be reading it.
        var ownedStringArguments = new List<IntPtr>();
        var variadicCount = IsVariadic ? context.Arguments.Count - callableCount : 0;
        var convertedArguments = new object?[_parameters.Count + variadicCount];
        var bufferBackedParameters = new List<(int Index, NativeFunctionParameterDefinition Parameter, NativeBuffer Buffer)>();
        var callerArgumentIndex = 0;

        for (var index = 0; index < _parameters.Count; index++)
        {
            var parameter = _parameters[index];

            if (parameter.IsInlineBuffer)
            {
                convertedArguments[index] = Array.CreateInstance(
                    parameter.ClrType.GetElementType()!,
                    parameter.InlineBufferLength!.Value);
                continue;
            }

            if (parameter.IsSynthesizedLength)
            {
                convertedArguments[index] = TypeConversion.TryConvert(
                    _parameters[index - 1].InlineBufferLength!.Value, parameter.ClrType, out var length)
                    ? length
                    : NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Out)
            {
                convertedArguments[index] = NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            var value = context.Arguments[callerArgumentIndex];
            var argumentIndex = callerArgumentIndex;
            callerArgumentIndex++;

            if (parameter.Callback is { } callbackDefinition)
            {
                if (value is not IShellCallable callable)
                {
                    throw context.CreateDiagnostic(
                        code: "tosh.runtime.native_callback_expects_function",
                        title: $"Parameter '{parameter.Name}' of '{ModuleName}.{Name}' expects the callback '{callbackDefinition.Name}'.",
                        argumentIndex: argumentIndex,
                        label: $"pass a function reference such as '&my_handler'");
                }

                var thunk = NativeCallbackThunkFactory.Create(
                    callbackDefinition, callable, context, Environment.CurrentManagedThreadId);

                // Rooted for the life of the library: a callee that stores the
                // pointer (GLFW's window callbacks) outlives this call, and a
                // collected thunk leaves native code calling freed memory.
                NativeCallbackThunkFactory.Root(Binding, thunk);

                convertedArguments[index] = thunk;
                continue;
            }

            // An input `cstring` this call owns, so a returned pointer into it can be
            // decoded before the memory goes away.
            if (parameter.OwnsCStringInput)
            {
                var owned = value is null ? IntPtr.Zero : Marshal.StringToHGlobalAnsi(value.ToString());

                if (owned != IntPtr.Zero)
                {
                    ownedStringArguments.Add(owned);
                }

                convertedArguments[index] = owned;
                continue;
            }

            // `ref cstring` — the slot holds a `char*` going in as well as coming
            // out, so the incoming string has to exist in native memory for the
            // duration of the call. This allocation *is* tosh's, so unlike the
            // pointer the callee may leave in its place, it is freed afterwards
            // (`TS-P3-26`).
            if (parameter.IsCStringPointer && parameter.PassingMode == NativeParameterPassingMode.Ref)
            {
                var incoming = value switch
                {
                    null => IntPtr.Zero,
                    IntPtr existing => existing,
                    NativeBuffer buffer => buffer.Pointer,
                    _ => Marshal.StringToHGlobalAnsi(value.ToString()),
                };

                if (value is not (null or IntPtr or NativeBuffer))
                {
                    ownedStringArguments.Add(incoming);
                }

                convertedArguments[index] = incoming;
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Ref && value is NativeBuffer nativeBuffer)
            {
                // Both the seeding read and the write-back below go through raw
                // pointers, so the buffer's own bounds checks do not apply. An
                // undersized buffer would read adjacent heap and then corrupt it.
                var required = NativeInteropUtilities.SizeOf(parameter.ClrType);

                if (nativeBuffer.ByteLength < required)
                {
                    throw context.CreateDiagnostic(
                        code: "tosh.runtime.native_buffer_range",
                        title: $"'{parameter.Name}' needs a {required}-byte buffer but received {nativeBuffer.ByteLength} bytes.",
                        argumentIndex: callerArgumentIndex - 1,
                        label: $"allocate with 'alloc buf = {parameter.TypeName}'");
                }

                convertedArguments[index] = NativeInteropUtilities.ReadValue(parameter.ClrType, nativeBuffer.Pointer);
                bufferBackedParameters.Add((index, parameter, nativeBuffer));
                continue;
            }

            if (parameter.PassingMode == NativeParameterPassingMode.Ref && value is null)
            {
                convertedArguments[index] = NativeInteropUtilities.CreateDefaultValue(parameter.ClrType);
                continue;
            }

            if (!TypeConversion.TryConvert(value, parameter.ClrType, out var converted))
            {
                throw context.CreateDiagnostic(
                    code: "tosh.runtime.native_argument_type_conversion_failed",
                    title: $"Argument {argumentIndex + 1} for native function '{ModuleName}.{Name}' could not be converted to '{parameter.TypeName}'.",
                    argumentIndex: argumentIndex,
                    label: $"argument {argumentIndex + 1} expects {parameter.TypeName}");
            }

            convertedArguments[index] = converted;
        }

        // The variadic tail. These have no declared parameter to convert against, so
        // they are promoted the way C promotes them and passed as they are — the
        // delegate built for this call shape has matching slots (`TS-P3-24`).
        for (var index = 0; index < variadicCount; index++)
        {
            var argument = context.Arguments[callableCount + index];
            convertedArguments[_parameters.Count + index] = argument switch
            {
                bool flag => flag ? 1 : 0,
                byte or sbyte or short or ushort or char => Convert.ToInt32(argument, CultureInfo.InvariantCulture),
                float single => (double)single,
                NativeBuffer buffer => buffer.Pointer,
                null => IntPtr.Zero,
                _ => argument,
            };
        }

        object? result;
        int errno;

        // A callback cannot throw across the native frames it runs on, so it
        // records its failure and returns a default instead. This scope is
        // where that failure becomes an exception again, once the native frames
        // are gone and throwing is legal.
        using (var callbackScope = new NativeCallbackScope())
        {
            try
            {
                result = ResolveDelegate(convertedArguments).DynamicInvoke(convertedArguments);

                // Must be read before any other managed work: the captured value is
                // per-thread and the next P/Invoke overwrites it.
                errno = Marshal.GetLastPInvokeError();
            }
            catch (TargetInvocationException exception) when (exception.InnerException is not null)
            {
                throw new InvalidOperationException(exception.InnerException.Message, exception.InnerException);
            }

            // Takes precedence over the native return value: a call whose
            // callback failed did not do what the script asked, whatever the
            // library reported.
            if (callbackScope.Failure is { } failure)
            {
                throw failure;
            }
        }

        // Decode before releasing, and in this order: a `char*` the callee returns
        // very often points *into* an input string, so the decode has to happen while
        // that memory is still ours. Doing it later — at projection time — read freed
        // bytes and produced convincing garbage.
        for (var index = 0; index < _parameters.Count; index++)
        {
            if (_parameters[index] is { IsCStringPointer: true } && convertedArguments[index] is IntPtr decoded)
            {
                convertedArguments[index] = decoded == IntPtr.Zero
                    ? null
                    : Marshal.PtrToStringAnsi(decoded);
            }
        }

        // The return value needs the same treatment for the same reason: `strsep`
        // returns a `char*` into the very buffer it was given, so decoding it after
        // the release would read freed bytes.
        if (ownedStringArguments.Count > 0 &&
            _return is { Kind: NativeFunctionReturnKind.CString } &&
            result is IntPtr returned)
        {
            result = returned == IntPtr.Zero ? null : Marshal.PtrToStringAnsi(returned);
        }

        // Only what this call allocated is freed — never what the callee put in its
        // place, whose allocator is unknowable from here.
        foreach (var owned in ownedStringArguments)
        {
            Marshal.FreeHGlobal(owned);
        }

        foreach (var bufferBackedParameter in bufferBackedParameters)
        {
            NativeInteropUtilities.WriteValue(bufferBackedParameter.Buffer.Pointer, convertedArguments[bufferBackedParameter.Index]);
        }

        // The synthesized length of a buffer[n] is plumbing, not a result.
        var byRefParameters = _parameters
            .Select((parameter, index) => (Parameter: parameter, Index: index))
            .Where(static entry =>
                entry.Parameter.PassingMode != NativeParameterPassingMode.In &&
                !entry.Parameter.IsSynthesizedLength)
            .ToArray();

        // The success contract decides whether we throw. It is orthogonal to the
        // projection below, which decides what a successful call yields.
        var convention = _return?.Convention ?? NativeErrorConvention.None;

        if (convention != NativeErrorConvention.None &&
            !await IsSuccessAsync(convention, result, context.CancellationToken))
        {
            var failure = new NativeError(Binding.Target, SymbolName, result, errno);

            // Marks this as a *thrown value* rather than an incidental runtime
            // exception. The engine's expression-level handlers rethrow anything
            // carrying it, so `catch (e)` binds the NativeError itself and
            // `$e.Errno` works — without it the error was flattened to a
            // ToshDiagnosticException before any catch could see it.
            failure.Data["tosh.thrown"] = true;

            // Without a span the renderer underlines the start of the script
            // rather than the failing call.
            if (context.Invocation?.CommandSpan is { } callSpan)
            {
                failure.Span = callSpan;
            }

            throw failure;
        }

        // `count` carries the true length of an inline buffer. readlink(2) does
        // not NUL-terminate its output, so without this the decoded string would
        // trail whatever was previously in the buffer.
        WarnIfCountLooksLikeANarrowFailure(result);

        var bufferLength = convention == NativeErrorConvention.Count ? ToInt32(result) : (int?)null;

        if ((_return is null || _return.ClrType == typeof(void)) && byRefParameters.Length == 0)
        {
            yield break;
        }

        if (byRefParameters.Length == 1 &&
            (convention != NativeErrorConvention.None || _return is null || _return.ClrType == typeof(void)))
        {
            // A checked call has already consumed its return value as the
            // pass/fail signal, so the out parameter is the result.
            yield return ProjectByRefValue(byRefParameters[0].Parameter, convertedArguments[byRefParameters[0].Index], bufferLength);
            yield break;
        }

        if (byRefParameters.Length == 0)
        {
            // `TS-P2-88`. A checked call spends its return value on the success
            // decision above, so yielding it again puts a status code into the
            // pipeline: `LibC.chdir("/tmp")` emitted `0`, and a render loop
            // calling `SDL_SetRenderDrawColor` printed a column of zeroes under
            // the window. The multi-out path had always known this — see
            // `CreateCompositeResult`, which omits `ReturnValue` for the same
            // reason — and only this zero-out path disagreed.
            //
            // `count` is the deliberate exception, on both paths: a byte count is
            // a genuine result that happens to double as the error signal.
            //
            // `Predicate` (a `where (…)` contract) keeps yielding, which is the
            // *opposite* of what `CreateCompositeResult` does with it. That
            // asymmetry is left alone rather than resolved here: a custom
            // predicate is written precisely when the return is not a standard
            // status — `-> ptr where (_ != 0)` guards a handle the caller needs —
            // so dropping it would break the case it exists for.
            if (convention is not NativeErrorConvention.Ok)
            {
                yield return ConvertReturn(result, _return!);
            }

            yield break;
        }

        yield return CreateCompositeResult(result, convertedArguments, byRefParameters, _return, convention, bufferLength);
        await Task.CompletedTask;
    }

    private async ValueTask<bool> IsSuccessAsync(
        NativeErrorConvention convention,
        object? result,
        CancellationToken cancellationToken)
    {
        return convention switch
        {
            NativeErrorConvention.Ok => ToInt64(result) == 0,
            NativeErrorConvention.Count => ToInt64(result) >= 0,
            NativeErrorConvention.Predicate => _successPredicate is not null &&
                                               await _successPredicate(result, cancellationToken),
            _ => true,
        };
    }

    /// <summary>
    /// Flags the one case where a bare <c>count</c> cannot be trusted.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Bare <c>-&gt; count</c> reads the return as <c>ssize_t</c>. Bound to a function
    /// that really returns <c>int32_t</c>, a <c>-1</c> failure arrives as
    /// <c>4294967295</c>: writing <c>EAX</c> zeroes the upper half of <c>RAX</c>, so the
    /// sign never reaches the high bits. That is non-negative, the contract's
    /// <c>&gt;= 0</c> check passes, and a failed call is reported as an enormous count
    /// (<c>TS-P2-124</c>).
    /// </para>
    /// <para>
    /// Which is undetectable in general — a shared object carries no C signature to
    /// check the declaration against. But the *window* is detectable, and on Linux it
    /// is unreachable by the functions <c>count</c> exists for: <c>read</c> and
    /// <c>write</c> transfer at most <c>0x7ffff000</c> bytes, just below where a
    /// 32-bit negative lands. So a bare <c>count</c> yielding a value in
    /// <c>[2^31, 2^32)</c> is almost certainly a misdeclared width, and saying so
    /// costs a warning on a genuine multi-gigabyte count that no POSIX call returns.
    /// </para>
    /// <para>
    /// A warning rather than an error because the value is genuinely ambiguous, and
    /// because a library outside POSIX may legitimately return one. It names the fix,
    /// and it is hushable.
    /// </para>
    /// </remarks>
    private void WarnIfCountLooksLikeANarrowFailure(object? result)
    {
        if (_warn is null ||
            _return is not { Convention: NativeErrorConvention.Count, ClrType: var width } ||
            width != typeof(IntPtr))
        {
            return;
        }

        var value = ToInt64(result);

        if (value is < int.MaxValue + 1L or > uint.MaxValue)
        {
            return;
        }

        var asNarrow = unchecked((int)value);

        _warn(
            "tosh.native.count_width_suspect",
            $"'{ModuleName}.{Name}' returned {value}, which is {asNarrow} read as a 32-bit value.",
            $"'{SymbolName}' may return `int` rather than `ssize_t`. Declare it `-> int count` so the "
            + "failure is detected; bare `count` reads a pointer-sized return, and a 32-bit -1 arrives "
            + "as 4294967295. If the count is genuine: hush tosh.native.count_width_suspect");
    }

    private static long ToInt64(object? value) => value switch
    {
        null => 0,
        IntPtr pointer => pointer.ToInt64(),
        UIntPtr pointer => unchecked((long)pointer.ToUInt64()),
        IConvertible convertible => convertible.ToInt64(null),
        _ => 0,
    };

    private static int ToInt32(object? value)
    {
        var wide = ToInt64(value);
        return wide is > int.MaxValue or < int.MinValue ? int.MaxValue : (int)wide;
    }

    private static object CreateCompositeResult(
        object? returnValue,
        IReadOnlyList<object?> convertedArguments,
        IReadOnlyList<(NativeFunctionParameterDefinition Parameter, int Index)> byRefParameters,
        NativeFunctionReturnDefinition? @return,
        NativeErrorConvention convention,
        int? bufferLength)
    {
        IDictionary<string, object?> fields = new ExpandoObject();

        // A checked call has already spent its return value on the success
        // decision, so repeating it as `ReturnValue` is noise — except for
        // `count`, where the value is a genuine result.
        var includeReturnValue = @return is not null &&
                                 @return.ClrType != typeof(void) &&
                                 convention is NativeErrorConvention.None or NativeErrorConvention.Count;

        if (includeReturnValue)
        {
            fields["ReturnValue"] = ConvertReturn(returnValue, @return!);
        }

        foreach (var (parameter, index) in byRefParameters)
        {
            fields[parameter.Name] = ProjectByRefValue(parameter, convertedArguments[index], bufferLength);
        }

        return fields;
    }

    /// <summary>
    /// An inline <c>buffer[n]</c> comes back as raw bytes; the caller asked for a
    /// string.
    /// </summary>
    /// <param name="bufferLength">
    /// The true length when the call declared <c>-&gt; count</c>. Without it,
    /// decoding stops at the first NUL — correct for gethostname and getcwd, but
    /// wrong for readlink and read, which do not terminate their output.
    /// </param>
    private static object? ProjectByRefValue(
        NativeFunctionParameterDefinition parameter,
        object? value,
        int? bufferLength = null)
    {
        // `out`/`ref cstring` — the callee wrote a `char*` into the slot. The
        // string is *copied* out and the native bytes are left alone: tosh never
        // frees memory it did not allocate, because the allocator is the callee's
        // and unknowable from here (`TS-P3-26`).
        // Already decoded immediately after the call, while the memory it pointed at
        // was still alive.
        if (parameter.IsCStringPointer)
        {
            return value;
        }

        // A typed T[n] out-array is already the result; only a cstring buffer
        // needs decoding.
        if (!parameter.DecodeAsCString || value is not byte[] bytes)
        {
            return value;
        }

        int length;

        if (bufferLength is { } declared)
        {
            length = Math.Clamp(declared, 0, bytes.Length);
        }
        else
        {
            length = Array.IndexOf(bytes, (byte)0);
            if (length < 0) length = bytes.Length;
        }

        return NativeInteropUtilities.DecodeCString(bytes.AsSpan(0, length));
    }

    private static object? ConvertReturn(object? result, NativeFunctionReturnDefinition @return)
    {
        if (@return.Kind == NativeFunctionReturnKind.CString)
        {
            return result is IntPtr pointer
                ? (pointer == IntPtr.Zero ? null : Marshal.PtrToStringAnsi(pointer))
                : result;
        }

        // `count` marshals as ssize_t (pointer-sized) for ABI correctness, but a
        // count is a number, not an address — surfacing IntPtr would make every
        // caller convert before they could do arithmetic on it.
        if (@return.Convention == NativeErrorConvention.Count)
        {
            return ToInt64(result);
        }

        return result;
    }

    /// <summary>
    /// The delegate to call with these arguments.
    /// </summary>
    /// <remarks>
    /// A fixed binding has one delegate, built when the binding was reached. A
    /// variadic one cannot: C reads its tail according to what the caller pushed, so
    /// the signature is a property of the call and not of the declaration. The shape
    /// is derived from the converted arguments, cached, and handed to the same
    /// emitter a fixed binding uses — which is why this works at all, and why it is
    /// no riskier than the concrete-arity declarations it replaces (<c>TS-P3-24</c>).
    /// </remarks>
    private Delegate ResolveDelegate(object?[] arguments)
    {
        if (_delegate is not null)
        {
            return _delegate;
        }

        var tail = arguments.Skip(_parameters.Count)
            .Select(static argument => PromoteVariadicArgument(argument))
            .ToArray();

        var key = string.Join(
            "|",
            tail.Select(static parameter => parameter.ClrType.AssemblyQualifiedName));

        return _variadicDelegates.GetOrAdd(key, _ => CreateDelegate(
            Binding.Handle,
            Binding.Target,
            SymbolName,
            [.. _parameters, .. tail],
            _return?.ClrType,
            _callingConvention));
    }

    /// <summary>
    /// The parameter a variadic argument is passed as, after C's default argument
    /// promotions.
    /// </summary>
    /// <remarks>
    /// C promotes anything narrower than <c>int</c> to <c>int</c>, and <c>float</c> to
    /// <c>double</c>, before a variadic call — <c>va_arg(ap, int)</c> is what the
    /// callee reads for a <c>char</c>. Passing the narrow type would put the wrong
    /// number of bytes in the wrong place, so the promotions are applied here rather
    /// than left to whatever the value happened to be.
    /// </remarks>
    private static NativeFunctionParameterDefinition PromoteVariadicArgument(object? argument)
    {
        var type = argument switch
        {
            null => typeof(IntPtr),
            bool or byte or sbyte or short or ushort or char or int => typeof(int),
            uint => typeof(uint),
            long => typeof(long),
            ulong => typeof(ulong),
            float or double => typeof(double),
            string => typeof(string),
            IntPtr => typeof(IntPtr),
            NativeBuffer => typeof(IntPtr),
            _ => argument.GetType(),
        };

        return new NativeFunctionParameterDefinition(
            "…",
            type.Name,
            type,
            NativeParameterPassingMode.In);
    }

    private static Delegate CreateDelegate(
        IntPtr libraryHandle,
        string libraryPath,
        string symbolName,
        IReadOnlyList<NativeFunctionParameterDefinition> parameters,
        Type? returnType,
        CallingConvention callingConvention)
    {
        IntPtr export;

        try
        {
            export = NativeLibrary.GetExport(libraryHandle, symbolName);
        }
        catch (EntryPointNotFoundException notFound)
        {
            // `TS-P3-25`. A misspelled or mangled symbol is the second commonest
            // binding mistake, and it reached the reader as `tosh.runtime.error`
            // with no code of its own to match on.
            throw ToshDiagnosticException.Create(new ToshDiagnostic(
                Code: "tosh.native.entry_point_not_found",
                Title: $"Native library '{libraryPath}' exports no symbol named '{symbolName}'.",
                SourceName: string.Empty,
                SourceText: string.Empty,
                Span: default,
                Label: notFound.Message,
                Help: $"check the spelling, and that the symbol is exported — `nm -D --defined-only {libraryPath}` lists what is."));
        }
        var delegateType = NativeDelegateTypeFactory.GetOrCreate(
            parameters,
            returnType ?? typeof(void),
            callingConvention);
        return Marshal.GetDelegateForFunctionPointer(export, delegateType);
    }
}

internal static class NativeDelegateTypeFactory
{
    // Shares NativeInteropModule with NativeStructTypeFactory: delegate
    // signatures reference emitted raw-struct types, so both live in one
    // dynamic assembly.
    private static ModuleBuilder Module => NativeInteropModule.Module;
    private static readonly ConcurrentDictionary<string, Type> Cache = new(StringComparer.Ordinal);
    private static int _nextTypeId;

    public static Type GetOrCreate(IReadOnlyList<NativeFunctionParameterDefinition> parameters, Type returnType, CallingConvention callingConvention)
    {
        var key = string.Join("|", parameters.Select(static parameter => $"{parameter.DelegateParameterType.AssemblyQualifiedName}@{parameter.PassingMode}"))
                  + "->"
                  + returnType.AssemblyQualifiedName
                  + "@"
                  + callingConvention;

        return Cache.GetOrAdd(key, _ => Create(parameters, returnType, callingConvention));
    }

    private static Type Create(IReadOnlyList<NativeFunctionParameterDefinition> parameters, Type returnType, CallingConvention callingConvention)
    {
        var typeBuilder = Module.DefineType(
            "ToshNativeDelegate" + Interlocked.Increment(ref _nextTypeId),
            TypeAttributes.Class | TypeAttributes.Public | TypeAttributes.Sealed | TypeAttributes.AnsiClass | TypeAttributes.AutoClass,
            typeof(MulticastDelegate));

        var attributeConstructor = typeof(UnmanagedFunctionPointerAttribute).GetConstructor([typeof(CallingConvention)])
                                   ?? throw new InvalidOperationException("Unable to locate UnmanagedFunctionPointerAttribute constructor.");

        // SetLastError is what makes errno readable after the call. Without it
        // Marshal.GetLastPInvokeError() returns whatever the previous P/Invoke
        // left behind, so a failure diagnostic would name an unrelated error.
        var setLastError = typeof(UnmanagedFunctionPointerAttribute).GetField(
                               nameof(UnmanagedFunctionPointerAttribute.SetLastError))
                           ?? throw new InvalidOperationException("Unable to locate UnmanagedFunctionPointerAttribute.SetLastError.");

        typeBuilder.SetCustomAttribute(new CustomAttributeBuilder(
            attributeConstructor,
            [callingConvention],
            [setLastError],
            [true]));

        var constructor = typeBuilder.DefineConstructor(
            MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.RTSpecialName,
            CallingConventions.Standard,
            [typeof(object), typeof(IntPtr)]);
        constructor.SetImplementationFlags(MethodImplAttributes.Runtime | MethodImplAttributes.Managed);

        var invoke = typeBuilder.DefineMethod(
            "Invoke",
            MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.NewSlot | MethodAttributes.Virtual,
            returnType,
            parameters.Select(static parameter => parameter.DelegateParameterType).ToArray());
        invoke.SetImplementationFlags(MethodImplAttributes.Runtime | MethodImplAttributes.Managed);

        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var attributes = parameter.PassingMode switch
            {
                NativeParameterPassingMode.Out => ParameterAttributes.Out,
                NativeParameterPassingMode.Ref => ParameterAttributes.In | ParameterAttributes.Out,
                _ => ParameterAttributes.None,
            };
            invoke.DefineParameter(index + 1, attributes, parameter.Name);
        }

        return typeBuilder.CreateType()
               ?? throw new InvalidOperationException("Failed to create native delegate type.");
    }
}
