using System.Reflection;
using Tosh.Compiler;
using Tosh.Language.Binding;
using Tosh.Language;
using Tosh.Runtime;

namespace Tosh.Tests;

/// <summary>
/// A CLR type loaded by another test must not capture a ToastScript name — <c>TS-P2-39</c>.
/// </summary>
/// <remarks>
/// <para>
/// This is the deterministic reproduction the item went seven sightings without. The suite's
/// flakiest failure,
/// <c>GenericClassTests.Generic_class_user_interface_constraint_accepts_implementing_class</c>,
/// finally produced a stack trace during a full build:
/// </para>
/// <code>
/// 'Holder.item' produced a value that could not be converted to
/// 'ToshTest_19690daaafa34cb3821a9a4aa3de47f6.Circle'
///    at EnforceStrictBinding
///    at ValidateConstructorTypeArguments
/// </code>
/// <para>
/// That namespace is generated by <c>BoundUnitEmitterTests</c>, which compiles ToastScript into
/// dynamic assemblies named <c>ToshTest_{Guid}</c> — one of which declares
/// <c>class Circle extends Shape</c>. So the strict-binding check resolved the bare name
/// <c>Circle</c> against a CLR type emitted by an unrelated test, then rejected the ToastScript
/// <c>Circle</c> for not being that type.
/// </para>
/// <para>
/// Nothing about it is specific to <c>Circle</c>: bare type-name resolution scans loaded
/// assemblies, so any name a compiled-emitter test happens to use can capture the same name in an
/// interpreted test. It reproduces only when the emitting test runs first, which is why it looked
/// like load-dependent flakiness for so long and why it passes in isolation. The same shape was
/// recorded as the fifth sighting, where a probe class named <c>Widget</c> collided with
/// <c>Tosh.LspFixture.Widget</c> — this file's own probe, which is why it is now named
/// <c>CrossTestLeakProbe</c>. A test that emits a type into the default load context claims that
/// name for the rest of the process, so a probe must not use one another test might want
/// (<c>TS-P2-48</c>).
/// </para>
/// <para>
/// This test forces the order rather than hoping for it: emit the assembly, then run the script.
/// </para>
/// </remarks>
public sealed class CrossTestTypeLeakTests : IClassFixture<ToshRuntimeFixture>
{
    private readonly ToshRuntime _runtime;

    public CrossTestTypeLeakTests(ToshRuntimeFixture fixture) => _runtime = fixture.Runtime;

    /// <summary>
    /// Compiles <paramref name="source"/> into a dynamic assembly and loads it, exactly as
    /// <c>BoundUnitEmitterTests</c> does, so the process ends up holding CLR types with these
    /// names.
    /// </summary>
    private Assembly EmitAndLoad(string source)
    {
        var engine = new ToshEngine(_runtime.Language);
        var parse = engine.Parse(source, "<leak-emit>");
        Assert.Empty(parse.Diagnostics);

        var unit = Lowerer.Lower(parse, _runtime.Commands);
        var assemblyName = $"ToshTest_{Guid.NewGuid():N}";

        using var stream = new MemoryStream();
        BoundUnitEmitter.Emit(unit, assemblyName, stream);

        return Assembly.Load(stream.ToArray());
    }

    [Fact]
    public async Task A_generic_constraint_resolves_the_scripts_own_class()
    {
        // Load a CLR `Circle` first, the way a compiled-emitter test does.
        var emitted = EmitAndLoad(
            "hollow class Shape { prop Kind = \"shape\" }\nclass Circle extends Shape { prop Radius = 0 }");

        Assert.Contains(emitted.GetTypes(), type => type.Name == "Circle");

        // Now the interpreted script declares its *own* Circle and constrains against its own
        // interface. Before the fix this threw "produced a value that could not be converted to
        // 'ToshTest_….Circle'" — the constraint had bound to the emitted type.
        var engine = new ToshEngine(ToshRuntime.CreateDefault().Language);
        var results = await engine.ExecuteToListAsync(
            """
            interface IShape { func area() }
            class Circle fulfills IShape {
                func area() { return 3 }
            }
            class Holder<T>(item: T) where T: IShape {
                prop item: T = $item
            }

            var h = new Holder<Circle>(new Circle())
            echo ($h.item.area())
            """);

        Assert.Equal(3, results[0]);
    }

    [Fact]
    public async Task A_plain_annotation_resolves_the_scripts_own_class()
    {
        // The same collision without generics, so a fix aimed only at constraint validation does
        // not look like a fix for the whole problem.
        EmitAndLoad("class CrossTestLeakProbe { prop Name = \"emitted\" }");

        var engine = new ToshEngine(ToshRuntime.CreateDefault().Language);
        var results = await engine.ExecuteToListAsync(
            """
            class CrossTestLeakProbe { prop Name = "scripted" }
            var w: CrossTestLeakProbe = (new CrossTestLeakProbe())
            $w.Name
            """);

        Assert.Equal("scripted", results[0]);
    }
}
