using System.Text.Json;
using System.Text.RegularExpressions;
using Tosh.Runtime;

namespace Tosh.Tests;

/// <summary>
/// The checked-in editor grammars know every word the language has.
///
/// Three artefacts colour ToastScript outside the runtime: the VS Code TextMate
/// grammar, the extension's hover/completion data, and the GtkSourceView
/// language definition. All three are checked into git, so all three can be
/// *stale* — right when generated, wrong the moment a word is added and nobody
/// regenerates.
///
/// That is not hypothetical. Adding the bitwise operators (`TS-P3-14`) left the
/// editor underlining `bor` as an error in a file that ran correctly, which is
/// the worst failure a highlighter has: it accuses working code. Two of these
/// files are generated and one is hand-written, and the generated ones are no
/// safer, because generating them is a step a person has to remember.
///
/// This is the same guard `TS-P2-10` put on the runtime consumers, pointed at the
/// editor. It is deliberately a *word-presence* check and not a scope check: it
/// asks whether each artefact has heard of the word, not how it colours it.
/// Asserting colours here would duplicate the grammar in the test and break on
/// every legitimate re-scoping.
///
/// The direction matters, and follows `LanguageSurfaceParityTests` exactly: a
/// word in the registry and missing from an artefact is a finding. The reverse is
/// not checked, because these files also name all 279 built-in commands, which
/// are not registry words and belong there.
/// </summary>
public sealed class EditorSurfaceParityTests
{
    /// <summary>
    /// The VS Code grammar is regenerated by `scripts/generate-vscode-grammar.tosh`
    /// and the hover data by `--export-command-metadata --vscode`; `tosh.lang` is
    /// maintained by hand. A failure here names which.
    /// </summary>
    [Theory]
    [InlineData("editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json",
                "scripts/generate-vscode-grammar.tosh")]
    [InlineData("editor/vscode/tosh.tosh-lang/language-data.json",
                "tosh --export-command-metadata --vscode")]
    [InlineData("editor/gtksourceview/tosh.lang",
                "hand-maintained — add the word beside its neighbours")]
    public void Every_language_word_reaches_the_editor_grammars(string relativePath, string regenerateWith)
    {
        var text = File.ReadAllText(Path.Combine(RepositoryRoot(), relativePath));

        // Whole-word, where a word may contain `-` (`is-not`, `starts-with`, `name-of`)
        // and so `\b` is not the boundary — `not` must not match inside `is-not`, and
        // a word must not match inside a longer alternation entry.
        var missing = LanguageSurface.Words.Keys
            .Where(word => !Regex.IsMatch(text, $@"(?<![\w-]){Regex.Escape(word)}(?![\w-])"))
            .OrderBy(word => word, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            missing.Length == 0,
            $"{relativePath} does not know these language words:\n  "
            + string.Join("\n  ", missing)
            + $"\n\nRegenerate with: {regenerateWith}");
    }

    /// <summary>
    /// The negative control, and the reason the assertion above is worth anything.
    /// A search loose enough to find every real word would also "find" a word that
    /// is not there — these three are spelled like ToastScript words, contain real
    /// words as substrings, and appear in none of the artefacts.
    /// </summary>
    [Theory]
    [InlineData("editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json")]
    [InlineData("editor/vscode/tosh.tosh-lang/language-data.json")]
    [InlineData("editor/gtksourceview/tosh.lang")]
    public void A_word_the_language_does_not_have_is_not_found(string relativePath)
    {
        var text = File.ReadAllText(Path.Combine(RepositoryRoot(), relativePath));

        foreach (var absent in new[] { "bandy", "flagship", "not-quite" })
        {
            Assert.False(
                Regex.IsMatch(text, $@"(?<![\w-]){Regex.Escape(absent)}(?![\w-])"),
                $"{relativePath} matched '{absent}', which the language does not have — "
                + "the word search is too loose to prove anything.");
        }
    }

    /// <summary>
    /// The hover data is JSON the extension loads at startup, so a malformed file
    /// is a broken extension rather than a failed build. It is regenerated wholesale,
    /// which is exactly when a truncated write would go unnoticed.
    /// </summary>
    [Fact]
    public void The_extension_hover_data_is_well_formed()
    {
        using var document = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/language-data.json")));

        foreach (var section in new[] { "keywords", "specialVariables", "builtins" })
        {
            Assert.True(document.RootElement.TryGetProperty(section, out var value),
                $"language-data.json has no '{section}' section.");
            Assert.NotEmpty(value.EnumerateObject());
        }
    }

    /// <summary>
    /// The grammar rules that colour constructs a regex alone cannot recognise.
    ///
    /// These exist because of a specific way this has gone wrong twice. A fix
    /// written into `tosh.tmLanguage.json` — which is *generated* — survives until
    /// the next regeneration and then vanishes without a trace, and the vanishing
    /// looks exactly like the fix never having been made. Record keys and the
    /// `path?` optional marker were both recorded as fixed on `TS-P3-12` and were
    /// both measurably unscoped afterwards, for that reason.
    ///
    /// So this asserts the rules are present in the *checked-in artefact*, which
    /// is what the editor actually loads. A regeneration that loses them fails
    /// here rather than quietly shipping.
    /// </summary>
    [Theory]
    // A parameter list is a region, so an untyped `func f(other)` can be told from
    // a call `greet(name)` — which a regex cannot do.
    [InlineData("signature-body")]
    [InlineData("signature-parameter")]
    // Balanced inner parens, so `cb: func(int) -> int` cannot end the signature early.
    [InlineData("nested-parens")]
    // Collection literals are regions, so a key can be told from a defaulted parameter.
    [InlineData("record-literal")]
    [InlineData("collection-key")]
    // `raw callback Name(...)` declares a type, so the name colours like `trait Name`.
    [InlineData("callback-definition")]
    // `catch (e)` binds a variable that no other rule can claim: the parameter rule
    // requires a following colon, and a catch binding has none.
    [InlineData("catch-binding")]
    public void The_structural_grammar_rules_are_present(string ruleName)
    {
        using var grammar = JsonDocument.Parse(File.ReadAllText(
            Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json")));

        Assert.True(
            grammar.RootElement.GetProperty("repository").TryGetProperty(ruleName, out _),
            $"The grammar has no '{ruleName}' rule. If it was just regenerated, the fix was "
            + "written into the generated JSON rather than into "
            + "scripts/generate-vscode-grammar.tosh, and regenerating dropped it.");
    }

    /// <summary>
    /// A sign glued to a digit belongs to the literal, which is the language's own
    /// rule (`TOAST-0115`, `TOAST-0121`). Before this, the sign matched no rule at
    /// all and rendered in the plain foreground while its digits were coloured:
    /// `Cancel = -6` in two colours, 98 times in the user's libraries.
    ///
    /// The lookbehind is the load-bearing half. Without it the rule would claim the
    /// `-5` of `$a-5` and `f()-5`, which are subtractions.
    /// </summary>
    [Fact]
    public void A_signed_numeric_literal_keeps_its_sign()
    {
        using var grammar = JsonDocument.Parse(File.ReadAllText(
            Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json")));

        var patterns = grammar.RootElement
            .GetProperty("repository").GetProperty("numeric").GetProperty("patterns")
            .EnumerateArray()
            .Select(rule => rule.TryGetProperty("match", out var m) ? m.GetString() ?? string.Empty : string.Empty)
            .ToArray();

        var signed = patterns.Where(match => match.Contains("[-+]", StringComparison.Ordinal)).ToArray();

        Assert.True(signed.Length >= 2, "The numeric rules no longer match a signed literal.");
        Assert.All(signed, match => Assert.Contains("(?<!", match, StringComparison.Ordinal));
    }

    /// <summary>
    /// A keyword must not eat the head of a hyphenated builtin. `native` is a
    /// keyword and `native-free` is a command, and a word boundary sits happily
    /// before a hyphen — so the keyword rule matched first and left `-free` scoped
    /// as nothing.
    ///
    /// Both halves are checked because either one alone leaves it broken: the
    /// keyword rule has to decline, and the command rules' keyword exclusion has to
    /// stop excluding it.
    /// </summary>
    [Fact]
    public void A_keyword_does_not_claim_the_head_of_a_hyphenated_builtin()
    {
        var grammarText = File.ReadAllText(
            Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json"));

        using var grammar = JsonDocument.Parse(grammarText);

        var controlFlow = grammar.RootElement
            .GetProperty("repository").GetProperty("control-flow").GetProperty("match").GetString() ?? string.Empty;

        Assert.Contains("(?<!-)", controlFlow, StringComparison.Ordinal);
        Assert.Contains("(?!-[A-Za-z])", controlFlow, StringComparison.Ordinal);

        // And the command rules' keyword exclusion lets the whole name through.
        Assert.Contains(@"\b(?!-))", grammarText, StringComparison.Ordinal);
    }

    /// <summary>
    /// The specific regression that made the parameter rule useless: it demanded a
    /// following <c>:</c>, so every untyped parameter stayed uncoloured — 243 tokens
    /// in the user's own libraries. Asserting the rule merely *exists* would pass on
    /// a rule that had quietly regained the requirement.
    /// </summary>
    [Fact]
    public void The_parameter_rule_does_not_require_a_type_annotation()
    {
        using var grammar = JsonDocument.Parse(File.ReadAllText(
            Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json")));

        var match = grammar.RootElement
            .GetProperty("repository")
            .GetProperty("signature-parameter")
            .GetProperty("match")
            .GetString();

        Assert.NotNull(match);
        Assert.DoesNotContain("(?=:", match);
        // And the optional marker is part of the name, or `path?` goes unscoped.
        Assert.Contains(@"\??", match);
    }

    private static string RepositoryRoot() =>
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../"));
}
