using System.Text.Json;
using System.Text.RegularExpressions;
using Tosh.Runtime;

namespace Tosh.Tests;

/// <summary>
/// The checked-in editor grammars know every word the language has.
///
/// Three artefacts colour ToastScript outside the runtime: the VS Code TextMate
/// grammar, the extension's hover/completion data, and the GtkSourceView
/// language definition. All three are checked into git, so all three can be
/// *stale* — right when generated, wrong the moment a word is added and nobody
/// regenerates.
///
/// That is not hypothetical. Adding the bitwise operators (`TS-P3-14`) left the
/// editor underlining `bor` as an error in a file that ran correctly, which is
/// the worst failure a highlighter has: it accuses working code. Two of these
/// files are generated and one is hand-written, and the generated ones are no
/// safer, because generating them is a step a person has to remember.
///
/// This is the same guard `TS-P2-10` put on the runtime consumers, pointed at the
/// editor. It is deliberately a *word-presence* check and not a scope check: it
/// asks whether each artefact has heard of the word, not how it colours it.
/// Asserting colours here would duplicate the grammar in the test and break on
/// every legitimate re-scoping.
///
/// The direction matters, and follows `LanguageSurfaceParityTests` exactly: a
/// word in the registry and missing from an artefact is a finding. The reverse is
/// not checked, because these files also name all 279 built-in commands, which
/// are not registry words and belong there.
/// </summary>
public sealed class EditorSurfaceParityTests
{
    /// <summary>
    /// The VS Code grammar is regenerated by `scripts/generate-vscode-grammar.tosh`
    /// and the hover data by `--export-command-metadata --vscode`; `tosh.lang` is
    /// maintained by hand. A failure here names which.
    /// </summary>
    [Theory]
    [InlineData("editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json",
                "scripts/generate-vscode-grammar.tosh")]
    [InlineData("editor/vscode/tosh.tosh-lang/language-data.json",
                "tosh --export-command-metadata --vscode")]
    [InlineData("editor/gtksourceview/tosh.lang",
                "hand-maintained — add the word beside its neighbours")]
    public void Every_language_word_reaches_the_editor_grammars(string relativePath, string regenerateWith)
    {
        var text = File.ReadAllText(Path.Combine(RepositoryRoot(), relativePath));

        // Whole-word, where a word may contain `-` (`is-not`, `starts-with`, `name-of`)
        // and so `\b` is not the boundary — `not` must not match inside `is-not`, and
        // a word must not match inside a longer alternation entry.
        var missing = LanguageSurface.Words.Keys
            .Where(word => !Regex.IsMatch(text, $@"(?<![\w-]){Regex.Escape(word)}(?![\w-])"))
            .OrderBy(word => word, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            missing.Length == 0,
            $"{relativePath} does not know these language words:\n  "
            + string.Join("\n  ", missing)
            + $"\n\nRegenerate with: {regenerateWith}");
    }

    /// <summary>
    /// The negative control, and the reason the assertion above is worth anything.
    /// A search loose enough to find every real word would also "find" a word that
    /// is not there — these three are spelled like ToastScript words, contain real
    /// words as substrings, and appear in none of the artefacts.
    /// </summary>
    [Theory]
    [InlineData("editor/vscode/tosh.tosh-lang/syntaxes/tosh.tmLanguage.json")]
    [InlineData("editor/vscode/tosh.tosh-lang/language-data.json")]
    [InlineData("editor/gtksourceview/tosh.lang")]
    public void A_word_the_language_does_not_have_is_not_found(string relativePath)
    {
        var text = File.ReadAllText(Path.Combine(RepositoryRoot(), relativePath));

        foreach (var absent in new[] { "bandy", "flagship", "not-quite" })
        {
            Assert.False(
                Regex.IsMatch(text, $@"(?<![\w-]){Regex.Escape(absent)}(?![\w-])"),
                $"{relativePath} matched '{absent}', which the language does not have — "
                + "the word search is too loose to prove anything.");
        }
    }

    /// <summary>
    /// The hover data is JSON the extension loads at startup, so a malformed file
    /// is a broken extension rather than a failed build. It is regenerated wholesale,
    /// which is exactly when a truncated write would go unnoticed.
    /// </summary>
    [Fact]
    public void The_extension_hover_data_is_well_formed()
    {
        using var document = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(RepositoryRoot(), "editor/vscode/tosh.tosh-lang/language-data.json")));

        foreach (var section in new[] { "keywords", "specialVariables", "builtins" })
        {
            Assert.True(document.RootElement.TryGetProperty(section, out var value),
                $"language-data.json has no '{section}' section.");
            Assert.NotEmpty(value.EnumerateObject());
        }
    }

    private static string RepositoryRoot() =>
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../"));
}
