namespace Tosh.Core.Commands;

public static class BuiltInCommands
{
    public static void RegisterDefaults(ShellCommandRegistry commands)
    {
        ArgumentNullException.ThrowIfNull(commands);

        commands.Register(new HelpCommand());
        commands.Register(new HelpCommand("man"));
        commands.Register(new AproposCommand());
        commands.Register(new ExitCommand());
        commands.Register(new ClearCommand());
        commands.Register(new HistoryCommand());
        commands.Register(new ViewCommand());
        commands.Register(new EchoCommand());
        commands.Register(new WriteCommand());
        commands.Register(new WriteLineCommand());
        commands.Register(new PrintWorkingDirectoryCommand());
        commands.Register(new ChangeDirectoryCommand());
        commands.Register(new UnameCommand());
        commands.Register(new HostnameCommand());
        commands.Register(new WhoAmICommand());
        commands.Register(new IdCommand());
        commands.Register(new ListDirectoryCommand());
        commands.Register(new DfCommand());
        commands.Register(new DfCommand("mounts"));
        commands.Register(new DuCommand());
        commands.Register(new DuCommand("usage"));
        commands.Register(new DuCommand("disk-usage"));
        commands.Register(new FreeCommand());
        commands.Register(new UptimeCommand());
        commands.Register(new StatCommand());
        commands.Register(new FindCommand());
        commands.Register(new ReadLinkCommand());
        commands.Register(new RealPathCommand());
        commands.Register(new DirNameCommand());
        commands.Register(new BaseNameCommand());
        commands.Register(new SeqCommand());
        commands.Register(new SleepCommand());
        commands.Register(new PingCommand());
        commands.Register(new ProcessListCommand());
        commands.Register(new EnvironmentCommand());
        commands.Register(new WhichCommand());
        commands.Register(new WhichCommand("whence"));
        commands.Register(new CatCommand());
        commands.Register(new HeadCommand());
        commands.Register(new TailCommand());
        commands.Register(new WordCountCommand());
        commands.Register(new UniqueCommand());
        commands.Register(new CutCommand());
        commands.Register(new TranslateCommand());
        commands.Register(new GrepCommand());
        commands.Register(new FromJsonCommand());
        commands.Register(new FromCsvCommand());
        commands.Register(new FromXmlCommand());
        commands.Register(new ParseCommand());
        commands.Register(new MakeDirectoryCommand());
        commands.Register(new TouchCommand());
        commands.Register(new RemoveItemCommand());
        commands.Register(new CopyItemCommand());
        commands.Register(new MoveItemCommand());
        commands.Register(new ChmodCommand());
        commands.Register(new ChownCommand());
        commands.Register(new LinkCommand());
        commands.Register(new GetCommand());
        commands.Register(new GetCommand("select"));
        commands.Register(new GetCommand("pick"));
        commands.Register(new RenameCommand());
        commands.Register(new InspectCommand());
        commands.Register(new WhereCommand());
        commands.Register(new EachCommand());
        commands.Register(new FirstCommand());
        commands.Register(new LastCommand());
        commands.Register(new SkipCommand());
        commands.Register(new SortCommand());
        commands.Register(new SortCommand("sort-by"));
        commands.Register(new ReverseCommand());
        commands.Register(new CountCommand());
        commands.Register(new FlattenCommand());
        commands.Register(new DistinctCommand());
        commands.Register(new GroupByCommand());
        commands.Register(new TakeWhileCommand());
        commands.Register(new SkipWhileCommand());
        commands.Register(new TeeCommand());
        commands.Register(new SumCommand());
        commands.Register(new AverageCommand());
        commands.Register(new AverageCommand("avg"));
        commands.Register(new MinCommand());
        commands.Register(new MaxCommand());
        commands.Register(new DateCommand());
        commands.Register(new TimeSpanCommand());
        commands.Register(new ToJsonCommand());
        commands.Register(new ToCsvCommand());
        commands.Register(new SplitCommand());
        commands.Register(new JoinLinesCommand());
        commands.Register(new ReplaceCommand());
        commands.Register(new MatchCommand());
        commands.Register(new TemplateCommand());
        commands.Register(new HashCommand());
        commands.Register(new PathPredicateCommand("exists", "Checks whether each path exists.", "Exists", path => File.Exists(path) || Directory.Exists(path)));
        commands.Register(new PathPredicateCommand("is-file", "Checks whether each path is a file.", "IsFile", File.Exists));
        commands.Register(new PathPredicateCommand("is-dir", "Checks whether each path is a directory.", "IsDirectory", Directory.Exists));
        commands.Register(new PathPredicateCommand("is-link", "Checks whether each path is a symbolic link.", "IsLink", path => File.Exists(path) ? new FileInfo(path).LinkTarget is not null : Directory.Exists(path) && new DirectoryInfo(path).LinkTarget is not null));
        commands.Register(new MakeTempDirectoryCommand());
        commands.Register(new TemporaryFileCommand());
        commands.Register(new TypeOfCommand());
        commands.Register(new DescribeTypeCommand());
        commands.Register(new MembersCommand());
        commands.Register(new MethodsCommand());
        commands.Register(new ConstructorsCommand());
        commands.Register(new TypesCommand());
        commands.Register(new LoadAssemblyCommand());
        commands.Register(new CastCommand());
        commands.Register(new NewObjectCommand());
        commands.Register(new CallCommand());
        commands.Register(new ExportCommand());
        commands.Register(new UnsetCommand());
        commands.Register(new UnaliasCommand());
        commands.Register(new UndefCommand());
        commands.Register(new HistorySearchCommand());
        commands.Register(new XargsCommand());
    }
}
