using System.Text;
using System.Text.Json;

namespace Tosh.Runtime;

/// <summary>
/// Generates a LaTeX command reference appendix from a command metadata.
/// Output uses the same <c>\section</c>, <c>cmdbox</c>, <c>signature</c>,
/// <c>longtable</c>, <c>lstlisting</c>, and <c>notebox</c> patterns as
/// the hand-written ToastScript specification.
/// </summary>
public static class CommandLatexEmitter
{
    public static string Emit(IReadOnlyList<CommandMetadata> metadata)
    {
        var sb = new StringBuilder();

        sb.AppendLine("% ─── AUTO-GENERATED by Tosh CommandLatexEmitter ───────────────────────");
        sb.AppendLine("% Do not edit by hand. Regenerate with: dotnet run --project src/Tosh.Cli -- --export-command-metadata --latex");
        sb.AppendLine();

        string? currentCategory = null;

        foreach (var entry in metadata)
        {
            if (!string.Equals(entry.Category, currentCategory, StringComparison.Ordinal))
            {
                currentCategory = entry.Category;
                sb.AppendLine();
                sb.AppendLine($"\\section{{{EscapeLatex(currentCategory)}}}");
                sb.AppendLine();
            }

            EmitCommand(sb, entry);
        }

        return sb.ToString();
    }

    public static string EmitFromJson(string json)
    {
        var metadata = JsonSerializer.Deserialize(json, MetadataJsonContext.Default.IReadOnlyListCommandMetadata)
                       ?? throw new InvalidOperationException("Failed to deserialize command metadata.");
        return Emit(metadata);
    }

    private static void EmitCommand(StringBuilder sb, CommandMetadata entry)
    {
        var safeName = entry.Name;
        var labelName = safeName.Replace("-", "-");

        // Section heading with index entry
        sb.AppendLine($"\\subsection{{\\texttt{{{EscapeLatex(safeName)}}}}}");
        sb.AppendLine($"\\label{{ref:{labelName}}}");
        sb.AppendLine($"\\icmd{{{EscapeLatex(safeName)}}}");
        sb.AppendLine();

        // Stdlib bucket and shell-only badge — surface the library / shell-only
        // partition called out in docs/COMPILED_TOSH.md so the appendix mirrors
        // the eventual Tosh.Stdlib.* assembly layout.
        if (!string.IsNullOrWhiteSpace(entry.Stdlib))
        {
            sb.AppendLine($"\\textit{{Library: \\code{{Tosh.Stdlib.{EscapeLatex(entry.Stdlib)}}}}}");
            sb.AppendLine();
        }
        if (entry.IsShellOnly)
        {
            sb.AppendLine("\\textbf{[shell-only]} — only available inside an interactive TōSh session.");
            sb.AppendLine();
        }

        // Command box
        sb.AppendLine($"\\begin{{cmdbox}}{{{EscapeLatex(safeName)}}}");

        // Description
        sb.AppendLine(EscapeLatex(entry.Description));
        sb.AppendLine();

        // Aliases
        if (entry.Aliases.Count > 0)
        {
            var aliasStr = string.Join(", ", entry.Aliases.Select(a => $"\\code{{{EscapeLatex(a)}}}"));
            sb.AppendLine($"\\textit{{Aliases:}} {aliasStr}");
            sb.AppendLine();
        }

        // Signature
        sb.AppendLine("\\begin{signature}");
        sb.AppendLine(FormatUsage(entry.Usage));
        sb.AppendLine("\\end{signature}");
        sb.AppendLine();

        // Arguments table
        if (entry.Arguments.Count > 0)
        {
            sb.AppendLine("\\begin{tabular}{@{}>{\\ttfamily\\small\\raggedright\\arraybackslash}p{5cm} L{9cm}@{}}");
            sb.AppendLine("\\toprule");
            sb.AppendLine("\\textbf{Argument} & \\textbf{Description} \\\\");
            sb.AppendLine("\\midrule");

            foreach (var arg in entry.Arguments)
            {
                var req = arg.Required ? "" : " (optional)";
                var typeStr = arg.TypeName is not null ? $" \\textit{{({EscapeLatex(arg.TypeName)})}}" : "";
                var name = EscapeLatex(arg.Name);
                if (name.Contains('|'))
                    name = name.Replace("|", "|\\allowbreak ");
                if (name.StartsWith('['))
                    name = "{}" + name;
                sb.AppendLine($"{name} & {EscapeLatex(arg.Description)}{req}{typeStr} \\\\");
            }

            sb.AppendLine("\\bottomrule");
            sb.AppendLine("\\end{tabular}");
            sb.AppendLine();
        }

        // Options table
        if (entry.Options.Count > 0)
        {
            sb.AppendLine("\\begin{tabular}{@{}>{\\ttfamily\\small\\raggedright\\arraybackslash}p{5cm} L{9cm}@{}}");
            sb.AppendLine("\\toprule");
            sb.AppendLine("\\textbf{Flag / Option} & \\textbf{Description} \\\\");
            sb.AppendLine("\\midrule");

            foreach (var opt in entry.Options)
            {
                var syntax = EscapeLatex(opt.Syntax);
                if (syntax.Contains('|'))
                    syntax = syntax.Replace("|", "|\\allowbreak ");
                if (syntax.StartsWith('['))
                    syntax = "{}" + syntax;
                sb.AppendLine($"{syntax} & {EscapeLatex(opt.Description)} \\\\");
            }

            sb.AppendLine("\\bottomrule");
            sb.AppendLine("\\end{tabular}");
            sb.AppendLine();
        }

        // Pipeline input info
        if (entry.PipelineInput is { } pi)
        {
            var accepts = new List<string>();

            if (pi.AcceptsScalar) accepts.Add("scalar");
            if (pi.AcceptsRecord) accepts.Add("record");
            if (pi.AcceptsList) accepts.Add("list");
            if (pi.AcceptsTable) accepts.Add("table");

            if (accepts.Count > 0 || pi.Description is not null)
            {
                sb.AppendLine($"\\textbf{{Pipeline input:}} {(accepts.Count > 0 ? string.Join(", ", accepts) : "none")}");
                if (pi.Description is not null)
                {
                    sb.AppendLine($" --- {EscapeLatex(pi.Description)}");
                }

                sb.AppendLine();
            }
        }

        // Output description
        if (entry.Output is not null)
        {
            sb.AppendLine($"\\textbf{{Output:}} {EscapeLatex(entry.Output)}");
            sb.AppendLine();
        }

        // Examples
        if (entry.Examples.Count > 0)
        {
            sb.AppendLine("\\begin{lstlisting}");

            foreach (var ex in entry.Examples)
            {
                var comment = ex.Title is not null ? $"  # {ex.Title}" : "";
                sb.AppendLine($"{ex.Code}{comment}");
            }

            sb.AppendLine("\\end{lstlisting}");
            sb.AppendLine();
        }

        // Notes
        foreach (var note in entry.Notes)
        {
            sb.AppendLine("\\begin{notebox}");
            sb.AppendLine(EscapeLatex(note));
            sb.AppendLine("\\end{notebox}");
            sb.AppendLine();
        }

        sb.AppendLine("\\end{cmdbox}");
        sb.AppendLine();
    }

    /// <summary>
    /// Wraps a long usage/signature string for LaTeX, inserting line breaks
    /// at word boundaries when lines exceed the given width.
    /// </summary>
    private static string FormatUsage(string usage, int maxWidth = 72)
    {
        if (usage.Length <= maxWidth)
            return EscapeLatex(usage);

        var words = usage.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        var lineLen = 0;

        foreach (var word in words)
        {
            if (lineLen > 0 && lineLen + 1 + word.Length > maxWidth)
            {
                sb.Append(" \\\\\n\\quad ");
                lineLen = 2;
            }
            else if (lineLen > 0)
            {
                sb.Append(' ');
                lineLen++;
            }

            var escaped = EscapeLatex(word);

            // Allow LaTeX to break long pipe-delimited tokens
            if (word.Length > 28 && word.Contains('|'))
                escaped = escaped.Replace("|", "|\\allowbreak ");

            sb.Append(escaped);
            lineLen += word.Length;
        }

        return sb.ToString();
    }

    private static string EscapeLatex(string text)
    {
        // Escape LaTeX special characters in user-provided text content.
        // The emitter wraps text in LaTeX commands (\code{}, \texttt{}, etc.)
        // itself — this only escapes the data payload.
        var sb = new StringBuilder(text.Length + 16);

        foreach (var ch in text)
        {
            sb.Append(ch switch
            {
                '\\' => "\\textbackslash{}",
                '{' => "\\{",
                '}' => "\\}",
                '$' => "\\$",
                '&' => "\\&",
                '#' => "\\#",
                '_' => "\\_",
                '^' => "\\^{}",
                '~' => "\\textasciitilde{}",
                '%' => "\\%",
                _ => ch.ToString(),
            });
        }

        return sb.ToString();
    }
}
