namespace Tosh.Runtime;

/// <summary>
/// Marks a CLR static-class (<c>sealed abstract</c>) that was generated by
/// <c>Tosh.Compiler.BoundUnitEmitter</c> as the shell for a compiled tosh
/// <c>module</c> declaration. Applied at the <b>type</b> level (unlike
/// <see cref="ToshModuleAttribute"/> which is assembly-level) so that
/// <c>ToshHost.RegisterCompiledAssembly</c> can build a
/// <c>qualifiedName → Type</c> dictionary by scanning all types in the
/// compiled assembly without any name-mangling correlation.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class ToshModuleShellAttribute : Attribute
{
    public ToshModuleShellAttribute(string qualifiedName) => QualifiedName = qualifiedName;

    /// <summary>
    /// The fully-qualified tosh module path, e.g. <c>"Foo"</c> or
    /// <c>"Foo.Bar"</c>.
    /// </summary>
    public string QualifiedName { get; }
}
