<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Tosh.Compiler.IR\Tosh.Compiler.IR.csproj" />
    <ProjectReference Include="..\Tosh.Language\Tosh.Language.csproj" />
    <ProjectReference Include="..\Tosh.Runtime\Tosh.Runtime.csproj" />
    <ProjectReference Include="..\Tosh.Compiler.Runtime\Tosh.Compiler.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.NET.HostModel"
               HintPath="$(MSBuildSDKsPath)\..\Microsoft.NET.HostModel.dll"
               Private="true" />
    <Reference Include="System.Reflection.MetadataLoadContext"
               HintPath="$(MSBuildSDKsPath)\..\System.Reflection.MetadataLoadContext.dll"
               Private="true" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
